GET http://localhost:3001/listings

###

POST http://localhost:3001/dog_walker/new
Content-Type: application/json

{
    "text": "John Doe"
}

###

DELETE http://localhost:3001/listings/delete/64650fec68a07254682535a3


###

PUT http://localhost:3001/dog_walker/rating/64651abc0a1c19aa1b9b66a5

###
POST http://localhost:3001/api/user/signup
Content-Type: application/json

{
    "username": "big boy 319",
    "password": "Yeetus123."
}